Repository 0xMiden/miden-base, pull requests merged in 2025-06, with the labels that each got.

#1378 test: proving benchmarks
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  Makefile
  bin/bench-prover/Cargo.toml
  bin/bench-prover/README.md
  bin/bench-prover/benches/benchmarks.rs
  bin/bench-prover/src/bench_functions.rs
  bin/bench-prover/src/lib.rs
  bin/bench-prover/src/main.rs
  bin/bench-prover/src/utils.rs
Labels: no docs

#1423 chore: refresh winter-air
  Cargo.lock
Labels: no changelog, no docs

#1415 Prologue test for kernel section
  crates/miden-testing/src/kernel_tests/tx/test_prologue.rs
Labels: no changelog, no docs

#1414 chore: use semver instead of own parser
  Cargo.lock
  bin/proving-service/Cargo.toml
  bin/proving-service/src/proxy/worker.rs
Labels: no changelog, no docs

#1412 chore: revisit proxy's worker configuration
  CHANGELOG.md
  bin/proving-service/.env
  bin/proving-service/README.md
  bin/proving-service/src/commands/proxy.rs
  bin/proving-service/src/commands/update_workers.rs
  bin/proving-service/src/proxy/worker.rs
  packaging/prover-proxy/miden-prover-proxy.service
Labels: no docs

#1425 refactor: Add transaction kernel advice inputs wrapper
  CHANGELOG.md
  crates/miden-lib/src/transaction/inputs.rs
  crates/miden-lib/src/transaction/mod.rs
  crates/miden-objects/src/account/storage/partial.rs
  crates/miden-objects/src/asset/vault/mod.rs
  crates/miden-objects/src/errors.rs
  crates/miden-objects/src/note/location.rs
  crates/miden-objects/src/transaction/inputs.rs
  crates/miden-proving-service-client/src/proving_service/batch_prover.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_prologue.rs
  crates/miden-testing/src/mock_host.rs
  crates/miden-testing/src/tx_context/context.rs
  crates/miden-tx/src/executor/mod.rs
  crates/miden-tx/src/executor/notes_checker.rs
  crates/miden-tx/src/prover/mod.rs
Labels: no docs

#1433 feat: add note_args to TransactionContextBuilder
  crates/miden-testing/src/tx_context/builder.rs
Labels: no changelog, no docs

#1422 feat: rm NoteExecutionMode from from_account_id
  CHANGELOG.md
  crates/miden-lib/src/account/interface/test.rs
  crates/miden-lib/src/note/mod.rs
  crates/miden-objects/src/note/metadata.rs
  crates/miden-objects/src/note/note_tag.rs
  crates/miden-objects/src/testing/note.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_note.rs
  crates/miden-testing/src/kernel_tests/tx/test_tx.rs
  crates/miden-testing/tests/integration/scripts/send_note.rs
Labels: no docs

#1427 chore: RM proving service binary crate
  .github/actions/build_package/action.yml
  .github/workflows/package.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  bin/proving-service/.env
  bin/proving-service/Cargo.toml
  bin/proving-service/README.md
  bin/proving-service/build.rs
  bin/proving-service/grafana_dashboard.json
  bin/proving-service/prometheus.yml
  bin/proving-service/proto/proving_service.proto
  bin/proving-service/proto/worker_status.proto
  bin/proving-service/src/api/mod.rs
  bin/proving-service/src/api/prover.rs
  bin/proving-service/src/api/status.rs
  bin/proving-service/src/commands/mod.rs
  bin/proving-service/src/commands/proxy.rs
  bin/proving-service/src/commands/update_workers.rs
  bin/proving-service/src/commands/worker.rs
  bin/proving-service/src/error.rs
  bin/proving-service/src/generated/mod.rs
  bin/proving-service/src/generated/proving_service.rs
  bin/proving-service/src/generated/status.rs
  bin/proving-service/src/main.rs
  bin/proving-service/src/proxy/health_check.rs
  bin/proving-service/src/proxy/metrics.rs
  bin/proving-service/src/proxy/mod.rs
  bin/proving-service/src/proxy/status.rs
  bin/proving-service/src/proxy/update_workers.rs
  bin/proving-service/src/proxy/worker.rs
  bin/proving-service/src/utils.rs
  crates/miden-proving-service-client/Cargo.toml
  crates/miden-proving-service-client/README.md
  crates/miden-proving-service-client/build.rs
  crates/miden-proving-service-client/proto/proving_service.proto
  crates/miden-proving-service-client/src/lib.rs
  crates/miden-proving-service-client/src/proving_service/batch_prover.rs
  crates/miden-proving-service-client/src/proving_service/block_prover.rs
  crates/miden-proving-service-client/src/proving_service/generated/mod.rs
  crates/miden-proving-service-client/src/proving_service/generated/nostd/mod.rs
  crates/miden-proving-service-client/src/proving_service/generated/nostd/proving_service.rs
  crates/miden-proving-service-client/src/proving_service/generated/std/mod.rs
  crates/miden-proving-service-client/src/proving_service/generated/std/proving_service.rs
  crates/miden-proving-service-client/src/proving_service/mod.rs
  crates/miden-proving-service-client/src/proving_service/tx_prover.rs
  crates/miden-testing/src/tx_context/context.rs
  packaging/prover-proxy/miden-prover-proxy.service
  packaging/prover-proxy/postinst
  packaging/prover-proxy/postrm
  packaging/prover/miden-prover.service
  packaging/prover/postinst
  packaging/prover/postrm
  proto/proving_service.proto
  proto/worker_status.proto
Labels: no docs

#1442 Move account vault events from `api.masm` to `account.masm`
  crates/miden-lib/asm/kernels/transaction/api.masm
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
Labels: no changelog, no docs

#1447 feat: Add TLS config to Proving Service Client
  CHANGELOG.md
  Cargo.lock
  crates/miden-proving-service-client/Cargo.toml
  crates/miden-proving-service-client/src/lib.rs
  crates/miden-proving-service-client/src/proving_service/tx_prover.rs
Labels: no docs

#1440 Fix outdated `account::set_item` docs
  crates/miden-lib/asm/kernels/transaction/api.masm
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/miden/account.masm
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
  crates/miden-objects/src/note/assets.rs
  crates/miden-objects/src/testing/account_code.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_account.rs
Labels: no changelog, no docs

#1456 Bump vm crates to v0.15
  Cargo.lock
  Cargo.toml
Labels: no changelog, no docs

#1459 Forbid empty transactions
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm
  crates/miden-lib/src/errors/tx_kernel_errors.rs
  crates/miden-objects/src/errors.rs
  crates/miden-objects/src/transaction/proven_tx.rs
  crates/miden-testing/src/kernel_tests/block/proven_block_error.rs
  crates/miden-testing/src/kernel_tests/block/utils.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_account.rs
  crates/miden-testing/src/kernel_tests/tx/test_epilogue.rs
  crates/miden-testing/src/kernel_tests/tx/test_fpi.rs
  docs/src/transaction.md
Labels: no docs

#1463 Simplify named module assembly
  crates/miden-lib/src/account/interface/test.rs
  crates/miden-objects/src/testing/account_component.rs
  crates/miden-testing/src/kernel_tests/mod.rs
Labels: no changelog, no docs

#1464 Temporarily bump ACCOUNT_UPDATE_MAX_SIZE to 256 KiB
  CHANGELOG.md
  crates/miden-objects/src/constants.rs
Labels: no docs

#1479 Add unit tests for `InputNotes` and `OutputNotes` constructors
  crates/miden-objects/src/transaction/inputs.rs
  crates/miden-objects/src/transaction/inputs/account.rs
  crates/miden-objects/src/transaction/inputs/mod.rs
  crates/miden-objects/src/transaction/inputs/notes.rs
  crates/miden-objects/src/transaction/outputs.rs
Labels: no changelog, no docs

#1484 fix: Order of `proc_ptr`, `metadata_ptr` in account kernel comment
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
Labels: no changelog
