Repository 0xMiden/miden-base, pull requests merged in 2025-05, with the labels that each got.

#1300 fix: compare versions fix
  CHANGELOG.md
  Cargo.lock
  bin/proving-service/Cargo.toml
  bin/proving-service/src/proxy/worker.rs
Labels: no docs

#1304 Move `NullifierTree` and `BlockChain` from node
  CHANGELOG.md
  crates/miden-block-prover/src/tests/proposed_block_errors.rs
  crates/miden-block-prover/src/tests/proven_block_success.rs
  crates/miden-objects/src/block/blockchain.rs
  crates/miden-objects/src/block/mod.rs
  crates/miden-objects/src/block/nullifier_tree.rs
  crates/miden-objects/src/block/partial_nullifier_tree.rs
  crates/miden-objects/src/errors.rs
  crates/miden-objects/src/testing/chain_mmr.rs
  crates/miden-tx/src/testing/mock_chain/mod.rs
Labels: no docs

#1305 Rename `ChainMmr` to `PartialBlockChain`
  CHANGELOG.md
  crates/miden-block-prover/src/local_block_prover.rs
  crates/miden-block-prover/src/tests/proposed_block_errors.rs
  crates/miden-block-prover/src/tests/proposed_block_success.rs
  crates/miden-block-prover/src/tests/proven_block_success.rs
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/asm/kernels/transaction/lib/prologue.masm
  crates/miden-lib/src/transaction/inputs.rs
  crates/miden-lib/src/transaction/memory.rs
  crates/miden-objects/src/batch/input_output_note_tracker.rs
  crates/miden-objects/src/batch/proposed_batch.rs
  crates/miden-objects/src/block/block_inputs.rs
  crates/miden-objects/src/block/blockchain.rs
  crates/miden-objects/src/block/proposed_block.rs
  crates/miden-objects/src/errors.rs
  crates/miden-objects/src/lib.rs
  crates/miden-objects/src/testing/mod.rs
  crates/miden-objects/src/testing/partial_blockchain.rs
  crates/miden-objects/src/transaction/inputs.rs
  crates/miden-objects/src/transaction/mod.rs
  crates/miden-objects/src/transaction/partial_blockchain.rs
  crates/miden-tx-batch-prover/src/tests/proposed_batch.rs
  crates/miden-tx/src/executor/data_store.rs
  crates/miden-tx/src/testing/mock_chain/mod.rs
  crates/miden-tx/src/testing/tx_context/mod.rs
  crates/miden-tx/src/tests/kernel_tests/test_prologue.rs
Labels: no docs

#1308 Add safe `PartialBlockChain` constructor
  CHANGELOG.md
  crates/miden-objects/src/block/blockchain.rs
  crates/miden-objects/src/errors.rs
  crates/miden-objects/src/testing/chain_mmr.rs
  crates/miden-objects/src/transaction/partial_blockchain.rs
Labels: no docs

#1269 Stateful execution checker
  CHANGELOG.md
  Cargo.lock
  bin/bench-tx/bench-tx.json
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/kernels/transaction/main.masm
  crates/miden-lib/asm/shared/util/account_id.masm
  crates/miden-lib/build.rs
  crates/miden-lib/src/account/interface/mod.rs
  crates/miden-lib/src/errors/tx_kernel_errors.rs
  crates/miden-lib/src/note/well_known_note.rs
  crates/miden-lib/src/transaction/events.rs
  crates/miden-lib/src/transaction/mod.rs
  crates/miden-tx/src/executor/mast_store.rs
  crates/miden-tx/src/executor/mod.rs
  crates/miden-tx/src/executor/notes_checker.rs
  crates/miden-tx/src/host/mod.rs
  crates/miden-tx/src/host/tx_progress.rs
  crates/miden-tx/src/lib.rs
  crates/miden-tx/src/testing/tx_context/builder.rs
  crates/miden-tx/src/tests/mod.rs
Labels: no docs

#1307 Fix error when creating accounts with empty storage
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/src/errors/tx_kernel_errors.rs
  crates/miden-tx/src/tests/kernel_tests/mod.rs
  crates/miden-tx/src/tests/kernel_tests/test_account.rs
Labels: no docs

#1319 fix: replace deprecated #[clap(...)] with #[command(...)] and #[arg(...)]
  bin/proving-service/src/commands/mod.rs
  bin/proving-service/src/commands/proxy.rs
  bin/proving-service/src/commands/update_workers.rs
  bin/proving-service/src/commands/worker.rs
Labels: no changelog, no docs

#1328 chore: re-export `MastForestStore`
  crates/miden-tx/src/executor/mod.rs
  crates/miden-tx/src/lib.rs
Labels: no changelog, no docs

#1324 test: Use vendored library
  crates/miden-objects/src/note/assets.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/tx_context/builder.rs
Labels: no changelog, no docs

#1332 chore: Add Debian packaging workflow
  .github/actions/build_package/action.yml
  .github/workflows/package.yml
  bin/proving-service/README.md
  packaging/prover-proxy/miden-prover-proxy.service
  packaging/prover-proxy/postinst
  packaging/prover-proxy/postrm
  packaging/prover/miden-prover.service
  packaging/prover/postinst
  packaging/prover/postrm
Labels: no changelog, no docs

#1336 chore: Add Debian packaging action and workflow
  .github/actions/build_package/action.yml
  .github/workflows/package.yml
  bin/proving-service/README.md
  packaging/prover-proxy/miden-prover-proxy.service
  packaging/prover-proxy/postinst
  packaging/prover-proxy/postrm
  packaging/prover/miden-prover.service
  packaging/prover/postinst
  packaging/prover/postrm
Labels: no changelog, no docs

#1340 chore: Update Debian package worfklow to work with latest packaging files
  .github/actions/build_package/action.yml
Labels: no changelog, no docs

#1342 chore: Update package workflow to run on Ubuntu latest for ARM
  .github/workflows/package.yml
Labels: no changelog, no docs

#1343 chore: Fix ARM package workflow runs-on setting
  .github/workflows/package.yml
Labels: no changelog, no docs

#1344 chore: Fix worfklow arm label
  .github/workflows/package.yml
Labels: no changelog, no docs

#1345 chore: Fix Debian service files
  packaging/prover-proxy/miden-prover-proxy.service
  packaging/prover/miden-prover.service
Labels: no changelog, no docs

#1315 Use batch and block provers in `MockChain`
  CHANGELOG.md
  bin/proving-service/src/main.rs
  crates/miden-objects/src/account/delta/vault.rs
  crates/miden-objects/src/batch/account_update.rs
  crates/miden-objects/src/batch/batch_id.rs
  crates/miden-objects/src/block/blockchain.rs
  crates/miden-objects/src/block/partial_nullifier_tree.rs
  crates/miden-objects/src/block/proven_block.rs
  crates/miden-objects/src/errors.rs
  crates/miden-testing/Cargo.toml
  crates/miden-testing/src/kernel_tests/batch/proposed_batch.rs
  crates/miden-testing/src/kernel_tests/block/proposed_block_errors.rs
  crates/miden-testing/src/kernel_tests/block/proposed_block_success.rs
  crates/miden-testing/src/kernel_tests/block/proven_block_error.rs
  crates/miden-testing/src/kernel_tests/block/proven_block_success.rs
  crates/miden-testing/src/kernel_tests/block/utils.rs
  crates/miden-testing/src/kernel_tests/tx/test_fpi.rs
  crates/miden-testing/src/kernel_tests/tx/test_note.rs
  crates/miden-testing/src/kernel_tests/tx/test_prologue.rs
  crates/miden-testing/src/kernel_tests/tx/test_tx.rs
  crates/miden-testing/src/lib.rs
  crates/miden-testing/src/mock_chain/account.rs
  crates/miden-testing/src/mock_chain/chain.rs
  crates/miden-testing/src/mock_chain/mod.rs
  crates/miden-testing/src/mock_chain/proven_tx_ext.rs
  crates/miden-testing/src/tx_context/builder.rs
  crates/miden-testing/tests/integration/scripts/faucet.rs
  crates/miden-testing/tests/integration/scripts/p2id.rs
  crates/miden-testing/tests/integration/scripts/p2idr.rs
  crates/miden-testing/tests/integration/scripts/send_note.rs
  crates/miden-testing/tests/integration/scripts/swap.rs
Labels: no docs

#1326 Fix typos and update links
  CONTRIBUTING.md
  Cargo.toml
  LICENSE
  README.md
  bin/proving-service/src/proxy/mod.rs
  crates/miden-objects/README.md
  crates/miden-testing/src/mock_chain/chain.rs
  docs/book.toml
  docs/src/account.md
  docs/src/index.md
  docs/src/note.md
  docs/src/state.md
  docs/src/transaction.md
Labels: no changelog, no docs

#1351 fix: bench-tx execution
  bin/bench-tx/src/main.rs
Labels: no changelog, no docs

#1348 Remove `dead_code` flag
  crates/miden-testing/src/mock_chain/account.rs
Labels: no changelog, no docs

#1334 Update `TokenSymbol` encoding
  CHANGELOG.md
  crates/miden-lib/src/transaction/inputs.rs
  crates/miden-objects/src/asset/mod.rs
  crates/miden-objects/src/asset/token_symbol.rs
  crates/miden-objects/src/errors.rs
  crates/miden-objects/src/lib.rs
Labels: no docs

#1327 Move note inputs number to the note data section
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/api.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/asm/kernels/transaction/lib/prologue.masm
  crates/miden-lib/asm/miden/kernel_proc_offsets.masm
  crates/miden-lib/asm/miden/note.masm
  crates/miden-lib/src/errors/tx_kernel_errors.rs
  crates/miden-lib/src/transaction/errors.rs
  crates/miden-lib/src/transaction/inputs.rs
  crates/miden-lib/src/transaction/memory.rs
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
  crates/miden-objects/src/note/inputs.rs
  crates/miden-testing/src/kernel_tests/tx/test_note.rs
  crates/miden-tx/src/host/note_builder.rs
Labels: no docs

#1356 Refactor Debian packages
  .github/actions/build_package/action.yml
  bin/proving-service/.env
  bin/proving-service/README.md
  packaging/prover-proxy/miden-prover-proxy.service
  packaging/prover-proxy/postinst
  packaging/prover-proxy/postrm
  packaging/prover/miden-prover.service
  packaging/prover/postinst
  packaging/prover/postrm
Labels: no changelog, no docs

#1357 chore: Fix Debian package cp cmds on workflow
  .github/actions/build_package/action.yml
Labels: no changelog, no docs

#1359 chore: Move Debian env file and add default worker address to service file
  .github/actions/build_package/action.yml
  bin/proving-service/.env
  bin/proving-service/README.md
  packaging/prover-proxy/miden-prover-proxy.service
  packaging/prover-proxy/postinst
  packaging/prover-proxy/postrm
  packaging/prover/miden-prover.service
  packaging/prover/postinst
  packaging/prover/postrm
Labels: no changelog, no docs

#1352 Add the `clippy.toml` file
  clippy.toml
  crates/miden-objects/src/account/account_id/mod.rs
  crates/miden-objects/src/account/account_id/seed.rs
  crates/miden-objects/src/account/account_id/v0/mod.rs
  crates/miden-objects/src/batch/proven_batch.rs
Labels: no docs

#1354 Refactor tx benchmark to use `TransactionContext::execute`
  Cargo.lock
  bin/bench-tx/Cargo.toml
  bin/bench-tx/bench-tx.json
  bin/bench-tx/src/main.rs
  bin/bench-tx/src/utils.rs
Labels: no changelog, no docs

#1346 Add iterators over concrete asset types in `NoteAssets`
  CHANGELOG.md
  crates/miden-objects/src/asset/mod.rs
  crates/miden-objects/src/note/assets.rs
Labels: no docs

#1364 fix link + remove formatting for plural / possessive for readibility
  docs/src/account.md
  docs/src/asset.md
  docs/src/blockchain.md
  docs/src/component_templates.md
  docs/src/note.md
  docs/src/transaction.md
Labels: no changelog

#1311 refactor: Generalize how accounts are passed to the VM
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/api.masm
  crates/miden-lib/src/transaction/inputs.rs
  crates/miden-lib/src/transaction/mod.rs
  crates/miden-objects/src/account/code/header.rs
  crates/miden-objects/src/account/code/mod.rs
  crates/miden-objects/src/account/header.rs
  crates/miden-objects/src/account/mod.rs
  crates/miden-objects/src/account/partial.rs
  crates/miden-objects/src/account/storage/header.rs
  crates/miden-objects/src/account/storage/mod.rs
  crates/miden-objects/src/account/storage/partial.rs
  crates/miden-objects/src/asset/mod.rs
  crates/miden-objects/src/asset/vault.rs
  crates/miden-objects/src/asset/vault/partial.rs
  crates/miden-objects/src/block/account_witness.rs
  crates/miden-objects/src/transaction/inputs.rs
  crates/miden-objects/src/transaction/mod.rs
  crates/miden-objects/src/transaction/tx_args.rs
  crates/miden-testing/src/kernel_tests/tx/test_fpi.rs
  crates/miden-testing/src/kernel_tests/tx/test_note.rs
  crates/miden-testing/src/kernel_tests/tx/test_prologue.rs
  crates/miden-testing/src/mock_chain/chain.rs
  crates/miden-testing/src/tx_context/builder.rs
  crates/miden-tx/src/executor/mod.rs
  crates/miden-tx/src/host/mod.rs
  crates/miden-tx/src/prover/mast_store.rs
  crates/miden-tx/src/prover/mod.rs
Labels: no docs

#1353 Upgrade Miden VM to 0.14
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/bench-tx/src/main.rs
  crates/miden-lib/asm/kernels/transaction/api.masm
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/kernels/transaction/lib/asset.masm
  crates/miden-lib/asm/kernels/transaction/lib/asset_vault.masm
  crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm
  crates/miden-lib/asm/kernels/transaction/lib/faucet.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/asm/kernels/transaction/lib/note.masm
  crates/miden-lib/asm/kernels/transaction/lib/prologue.masm
  crates/miden-lib/asm/kernels/transaction/lib/tx.masm
  crates/miden-lib/asm/kernels/transaction/tx_script_main.masm
  crates/miden-lib/asm/miden/asset.masm
  crates/miden-lib/asm/miden/contracts/faucets/basic_fungible.masm
  crates/miden-lib/asm/miden/note.masm
  crates/miden-lib/asm/note_scripts/P2ID.masm
  crates/miden-lib/asm/note_scripts/P2IDR.masm
  crates/miden-lib/asm/note_scripts/SWAP.masm
  crates/miden-lib/asm/shared/util/account_id.masm
  crates/miden-lib/build.rs
  crates/miden-lib/src/errors/masm_error.rs
  crates/miden-lib/src/errors/mod.rs
  crates/miden-lib/src/errors/note_script_errors.rs
  crates/miden-lib/src/errors/tx_kernel_errors.rs
  crates/miden-lib/src/lib.rs
  crates/miden-objects/src/lib.rs
  crates/miden-testing/src/executor.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/kernel_tests/tx/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_account.rs
  crates/miden-testing/src/kernel_tests/tx/test_faucet.rs
  crates/miden-testing/src/kernel_tests/tx/test_fpi.rs
  crates/miden-testing/src/kernel_tests/tx/test_note.rs
  crates/miden-testing/src/kernel_tests/tx/test_tx.rs
  crates/miden-testing/src/mock_host.rs
  crates/miden-testing/src/tx_context/builder.rs
  crates/miden-testing/src/tx_context/context.rs
  crates/miden-testing/tests/integration/main.rs
  crates/miden-tx/src/errors/mod.rs
  crates/miden-tx/src/executor/mod.rs
  crates/miden-tx/src/executor/notes_checker.rs
  crates/miden-tx/src/host/mod.rs
  crates/miden-tx/src/prover/mod.rs
Labels: no docs

#1370 Doc updates
  docs/src/transaction.md
Labels: no changelog

#1377 Testing with `TransactionContext`: make debug mode the default for `execute`
  crates/miden-testing/src/tx_context/context.rs
Labels: no changelog, no docs

#1382 chore: update pingora & other deps
  Cargo.lock
  Cargo.toml
  Makefile
  bin/proving-service/Cargo.toml
  bin/proving-service/README.md
  bin/proving-service/src/proxy/mod.rs
  bin/proving-service/src/proxy/status.rs
Labels: no changelog, no docs

#1385 fix(objects): export types used in public apis
  crates/miden-objects/src/account/mod.rs
Labels: no changelog, no docs

#1386 chore: Fix Rust version in release workflow
  .github/actions/build_package/action.yml
  .github/workflows/package.yml
Labels: no changelog, no docs

#1389 Move `FungibleFaucetError` from `miden-objects` to `miden-lib`
  crates/miden-lib/src/account/faucets/mod.rs
  crates/miden-objects/src/errors.rs
  crates/miden-objects/src/lib.rs
Labels: no changelog, no docs

#1393 Allow NOOP and state-updating transactions in the same block
  CHANGELOG.md
  crates/miden-objects/src/block/proposed_block.rs
  crates/miden-testing/src/kernel_tests/batch/proposed_batch.rs
  crates/miden-testing/src/kernel_tests/block/proposed_block_success.rs
  crates/miden-testing/src/kernel_tests/block/utils.rs
Labels: no docs

#1396 Implement basic map in transaction kernel
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/lib/link_map.masm
  crates/miden-testing/src/kernel_tests/tx/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_link_map.rs
Labels: no docs
