Repository 0xMiden/miden-base, pull requests merged in 2025-03, with the labels that each got.

#1193 Pin cargo machete to a specific version
  .github/workflows/lint.yml
Labels: no changelog

#1186 feat: removed external dependencies from miden-objects
  crates/miden-objects/src/account/account_id/account_type.rs
  crates/miden-objects/src/account/account_id/id_prefix.rs
  crates/miden-objects/src/account/account_id/seed.rs
  crates/miden-objects/src/account/auth.rs
  crates/miden-objects/src/account/code/procedure.rs
  crates/miden-objects/src/account/delta/storage.rs
  crates/miden-objects/src/account/header.rs
  crates/miden-objects/src/account/storage/header.rs
  crates/miden-objects/src/account/storage/slot/type.rs
  crates/miden-objects/src/asset/fungible.rs
  crates/miden-objects/src/asset/nonfungible.rs
  crates/miden-objects/src/batch/account_update.rs
  crates/miden-objects/src/batch/input_output_note_tracker.rs
  crates/miden-objects/src/batch/note_tree.rs
  crates/miden-objects/src/block/account_update_witness.rs
  crates/miden-objects/src/block/account_witness.rs
  crates/miden-objects/src/block/note_tree.rs
  crates/miden-objects/src/block/nullifier_witness.rs
  crates/miden-objects/src/block/partial_nullifier_tree.rs
  crates/miden-objects/src/block/proposed_block.rs
  crates/miden-objects/src/lib.rs
  crates/miden-objects/src/note/assets.rs
  crates/miden-objects/src/note/details.rs
  crates/miden-objects/src/note/execution_hint.rs
  crates/miden-objects/src/note/inputs.rs
  crates/miden-objects/src/note/mod.rs
  crates/miden-objects/src/note/script.rs
  crates/miden-objects/src/transaction/chain_mmr.rs
  crates/miden-objects/src/transaction/executed_tx.rs
  crates/miden-objects/src/transaction/outputs.rs
  crates/miden-objects/src/transaction/proven_tx.rs
  crates/miden-objects/src/transaction/tx_args.rs
  crates/miden-objects/src/transaction/tx_witness.rs
Labels: no changelog

#1191 Updating account Id in the docs
  docs/architecture/account.md
Labels: no changelog

#1194 Format MASM
  crates/miden-lib/asm/kernels/transaction/api.masm
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/kernels/transaction/lib/asset.masm
  crates/miden-lib/asm/kernels/transaction/lib/asset_vault.masm
  crates/miden-lib/asm/kernels/transaction/lib/constants.masm
  crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm
  crates/miden-lib/asm/kernels/transaction/lib/faucet.masm
  crates/miden-lib/asm/kernels/transaction/lib/note.masm
  crates/miden-lib/asm/kernels/transaction/lib/prologue.masm
  crates/miden-lib/asm/kernels/transaction/lib/tx.masm
  crates/miden-lib/asm/kernels/transaction/main.masm
  crates/miden-lib/asm/miden/account.masm
  crates/miden-lib/asm/miden/asset.masm
  crates/miden-lib/asm/miden/contracts/auth/basic.masm
  crates/miden-lib/asm/miden/contracts/faucets/basic_fungible.masm
  crates/miden-lib/asm/miden/contracts/wallets/basic.masm
  crates/miden-lib/asm/miden/faucet.masm
  crates/miden-lib/asm/miden/kernel_proc_offsets.masm
  crates/miden-lib/asm/miden/note.masm
  crates/miden-lib/asm/miden/tx.masm
  crates/miden-lib/asm/note_scripts/P2ID.masm
  crates/miden-lib/asm/note_scripts/P2IDR.masm
  crates/miden-lib/asm/note_scripts/SWAP.masm
  crates/miden-lib/asm/shared/util/account_id.masm
Labels: no changelog

#1188 feat: removed external dependencies from miden-lib
  crates/miden-lib/src/note/scripts.rs
Labels: no changelog

#1205 docs: Add component template format docs
  docs/architecture/component_templates.md
Labels: no changelog

#1190 Update docs to support mdbook
  .github/workflows/book.yml
  .github/workflows/build.yml
  .github/workflows/docs.yml
  Makefile
  docs/.gitignore
  docs/architecture/limits.md
  docs/book.toml
  docs/img/roadmap.jpg
  docs/index.md
  docs/network/network.md
  docs/roadmap.md
  docs/src/EXPORTED.md
  docs/src/SUMMARY.md
  docs/src/account.md
  docs/src/asset.md
  docs/src/blockchain.md
  docs/src/img/account/account-definition.png
  docs/src/img/asset/asset-issuance.png
  docs/src/img/asset/asset-storage.png
  docs/src/img/blockchain/batching.png
  docs/src/img/blockchain/block.png
  docs/src/img/blockchain/execution.png
  docs/src/img/miden-architecture-core-concepts.gif
  docs/src/img/miden-architecture-state-progress.gif
  docs/src/img/network/Miden_node.png
  docs/src/img/network/architecture-overview.png
  docs/src/img/note/note-life-cycle.png
  docs/src/img/note/note.png
  docs/src/img/note/nullifier.png
  docs/src/img/state/account-db.png
  docs/src/img/state/note-db.png
  docs/src/img/state/nullifier-db.png
  docs/src/img/state/public-shared-state.png
  docs/src/img/state/state.png
  docs/src/img/transaction/local-vs-network-transaction.png
  docs/src/img/transaction/memory-layout-kernel.png
  docs/src/img/transaction/transaction-contexts.png
  docs/src/img/transaction/transaction-diagram.png
  docs/src/img/transaction/transaction-execution-process.png
  docs/src/img/transaction/transaction-flow.png
  docs/src/img/transaction/transaction-program.png
  docs/src/img/transaction/tx-overview.png
  docs/src/index.md
  docs/src/note.md
  docs/src/state.md
  docs/src/transaction.md
  scripts/check-docs.sh
  scripts/docs_requirements.txt
  scripts/serve-doc-site.sh
Labels: no changelog

#1203 Add Bech32 encoding to the account documentation.
  .github/workflows/book.yml
  docs/src/account.md
Labels: no changelog

#1215 refactor(templates): `tokensymbol` -> `token_symbol`
  crates/miden-objects/src/account/component/template/mod.rs
  crates/miden-objects/src/account/component/template/storage/mod.rs
  crates/miden-objects/src/account/component/template/storage/placeholder.rs
  docs/architecture/component_templates.md
Labels: no changelog

#1223 fix: Script builder newline
  crates/miden-lib/src/account/interface/component.rs
Labels: no changelog

#1232 Fix falcon event
  Cargo.lock
  crates/miden-lib/asm/miden/contracts/auth/basic.masm
  crates/miden-lib/src/transaction/errors.rs
  crates/miden-lib/src/transaction/events.rs
  crates/miden-tx/src/host/mod.rs
Labels: no changelog

#1233 Revert cargo machete pin
  .github/workflows/lint.yml
Labels: no changelog

#1238 Use crates.io versions for miden-vm dependencies
  Cargo.lock
  Cargo.toml
Labels: no changelog

#1236 Fix minor spelling of `receiver`
  crates/miden-block-prover/src/tests/utils.rs
Labels: no changelog

#1239 Final changes for mdbook
  .github/workflows/book.yml
  .github/workflows/build.yml
  docs/book.toml
Labels: no changelog

#1242 Add padding for inputs in `compute_inputs_commitment` procedure
  Cargo.lock
  crates/miden-lib/asm/miden/note.masm
  crates/miden-tx/src/tests/kernel_tests/test_note.rs
Labels: no changelog, no docs

#1245 chore: update axum and tokio in proving service
  Cargo.lock
  bin/proving-service/Cargo.toml
  bin/proving-service/src/proxy/health_check.rs
  bin/proving-service/src/proxy/update_workers.rs
  bin/proving-service/src/utils.rs
Labels: no changelog, no docs

#1251 refactor: Take `AsRef<NoteRecipient>` to extend expected output notes
  CHANGELOG.md
  crates/miden-objects/src/note/details.rs
  crates/miden-objects/src/note/mod.rs
  crates/miden-objects/src/transaction/tx_args.rs
  crates/miden-tx/src/testing/tx_context/builder.rs
  crates/miden-tx/src/tests/mod.rs
Labels: no docs

#1246 Changing some pictures and resizing
  docs/src/asset.md
  docs/src/img/asset/asset-issuance.png
  docs/src/img/asset/asset-storage.png
  docs/src/img/note/note-life-cycle.png
  docs/src/img/note/nullifier.png
  docs/src/img/state/nullifier-db.png
  docs/src/img/state/public-shared-state.png
  docs/src/img/transaction/transaction-program.png
  docs/src/note.md
  docs/src/state.md
  docs/src/transaction.md
Labels: no changelog

#1250 Hash keys in `StorageMap` before insertion into SMT
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
  crates/miden-objects/src/account/delta/storage.rs
  crates/miden-objects/src/account/storage/header.rs
  crates/miden-objects/src/account/storage/map.rs
  crates/miden-objects/src/account/storage/mod.rs
  crates/miden-objects/src/errors.rs
  crates/miden-tx/src/tests/kernel_tests/test_faucet.rs
Labels: no docs

#1249 feat: combine proxy url in update command
  CHANGELOG.md
  bin/proving-service/.env
  bin/proving-service/README.md
  bin/proving-service/src/commands/mod.rs
  bin/proving-service/src/commands/proxy.rs
  bin/proving-service/src/commands/update_workers.rs
  bin/proving-service/src/utils.rs
Labels: no docs

#1259 feat: add proof security level getter
  CHANGELOG.md
  crates/miden-objects/src/batch/proven_batch.rs
  crates/miden-objects/src/block/proven_block.rs
Labels: no docs
