Repository 0xMiden/miden-base, pull requests merged in 2025-07, with the labels that each got.

#1512 Remove stale MASM files in build.rs
  crates/miden-lib/build.rs
Labels: no changelog

#1478 Implement `LinkMap` iterator
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/lib/link_map.masm
  crates/miden-objects/src/account/delta/lexicographic_word.rs
  crates/miden-objects/src/account/delta/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_link_map.rs
  crates/miden-tx/src/host/link_map.rs
Labels: no docs

#1460 Implement in-kernel account delta for fungible assets
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm
  crates/miden-lib/asm/kernels/transaction/lib/asset_vault.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
  crates/miden-objects/src/account/delta/mod.rs
  crates/miden-objects/src/account/delta/vault.rs
  crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs
Labels: no docs

#1481 Implement in-kernel account delta for non fungible assets
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
  crates/miden-objects/src/account/delta/vault.rs
  crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs
Labels: no docs

#1491 Implement in-kernel account delta for storage maps
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/kernels/transaction/lib/account_delta.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/src/transaction/memory.rs
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
  crates/miden-objects/src/account/delta/mod.rs
  crates/miden-objects/src/account/delta/storage.rs
  crates/miden-objects/src/account/storage/map.rs
  crates/miden-objects/src/transaction/proven_tx.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs
  crates/miden-tx/src/host/link_map.rs
  crates/miden-tx/src/host/mod.rs
Labels: no docs

#1492 Refactor account delta nonce from `Option<Felt>` to `Felt`
  CHANGELOG.md
  crates/miden-lib/src/transaction/memory.rs
  crates/miden-objects/src/account/delta/mod.rs
  crates/miden-objects/src/account/delta/storage.rs
  crates/miden-objects/src/account/delta/vault.rs
  crates/miden-objects/src/account/mod.rs
  crates/miden-objects/src/errors.rs
  crates/miden-objects/src/transaction/proven_tx.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs
  crates/miden-testing/tests/integration/scripts/faucet.rs
  crates/miden-tx/src/errors/mod.rs
  crates/miden-tx/src/executor/mod.rs
  crates/miden-tx/src/host/account_delta_tracker.rs
Labels: no docs

#1525 fix: Re-add `ExecutionOptions` re-export
  crates/miden-tx/src/lib.rs
Labels: no changelog

#1530 Introduce `get_acct_procedure_ptr` method in `miden::memory`
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/kernels/transaction/lib/epilogue.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
Labels: kernels, no changelog

#1521 Track called procedures
  CHANGELOG.md
  crates/miden-lib/asm/kernels/transaction/api.masm
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/asm/miden/account.masm
  crates/miden-lib/asm/miden/kernel_proc_offsets.masm
  crates/miden-lib/src/transaction/memory.rs
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
  crates/miden-testing/src/kernel_tests/tx/test_account.rs
Labels: kernels

#1538 chore: Correct current typos and add a spellcheck workflow
  .github/workflows/lint.yml
  CONTRIBUTING.md
  Makefile
  _typos.toml
  crates/miden-lib/asm/kernels/transaction/lib/link_map.masm
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/asm/kernels/transaction/lib/prologue.masm
  crates/miden-lib/asm/kernels/transaction/lib/tx.masm
  crates/miden-lib/src/errors/tx_kernel_errors.rs
  crates/miden-lib/src/transaction/mod.rs
  crates/miden-objects/src/account/account_id/mod.rs
  crates/miden-objects/src/account/code/procedure.rs
  crates/miden-objects/src/note/note_tag.rs
  crates/miden-objects/src/transaction/tx_args.rs
  crates/miden-testing/src/kernel_tests/block/proposed_block_errors.rs
  crates/miden-testing/src/kernel_tests/mod.rs
  crates/miden-testing/src/kernel_tests/tx/test_account_delta.rs
  crates/miden-testing/src/kernel_tests/tx/test_link_map.rs
  crates/miden-testing/src/kernel_tests/tx/test_prologue.rs
  crates/miden-testing/src/mock_chain/proven_tx_ext.rs
  crates/miden-tx/src/executor/notes_checker.rs
  docs/src/account.md
Labels: no changelog, no docs

#1553 chore: Remove erroneous `#[cfg(any(feature = "testing", test))]`
  crates/miden-lib/src/lib.rs
Labels: no changelog

#1547 chore: Add `make install-tools`
  CONTRIBUTING.md
  Makefile
Labels: no changelog

#1475 Configure release-plz
  .github/workflows/release-plz-dry-run.yml
  .github/workflows/release-plz.yml
  .release-plz.toml
Labels: no changelog

#1587 fix: use async for miden-prover
  crates/miden-tx/Cargo.toml
Labels: no changelog

#1585 chore: optimize `mem_loadw` -> `mem_load` when possible
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
Labels: no changelog

#1605 Optimize use of lt/gt with u32lt/u32gt
  crates/miden-lib/asm/kernels/transaction/lib/memory.masm
  crates/miden-lib/asm/kernels/transaction/lib/tx.masm
  crates/miden-lib/src/transaction/procedures/kernel_v0.rs
Labels: no changelog

#1625 chore: update miden-vm version in `Cargo.toml`
  Cargo.toml
Labels: no changelog

#1650 chore: make `ERR_ACCOUNT_PROC_NOT_AUTH_PROC` more verbose
  crates/miden-lib/asm/kernels/transaction/lib/account.masm
  crates/miden-lib/src/errors/tx_kernel_errors.rs
Labels: no changelog
